### ISSUE TITLE
Java 11 no longer includes Java EE modules that old versions of sdkmanager references

### ISSUE THREAD

**Issue by kmayoral** [mindrunner/docker-android-sdk#74]
Thank you so much for the update to Java 11 yesterday, I was just in the process of updating our build process to 11 at the same time so perfect timing :)

It looks like that update may have broken the ability to use the current version of SDK tools that are included with this image however.

https://github.com/mindrunner/docker-android-sdk/blob/a216e209e2e2eb7bdac4c342d6077cff1dc664f3/tools/android-sdk-update.sh#L30

I think that line will need to be updated with 
```
https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
```

This is because sdkmanager appears to reference some Java EE modules like `java.xml.bind` that are no longer included in Java 11 at all.  (See: http://openjdk.java.net/jeps/320 and https://jaxenter.com/jdk-11-java-ee-modules-140674.html).

Here is a screenshot of my jenkins build using the latest image which led me down this path.
![Screen Shot 2021-08-03 at 11 42 51 AM](https://user-images.githubusercontent.com/801410/128069602-e102241f-fdeb-45d8-968f-18c19331ee20.png)

I haven't tested this hypothesis but based most of my assumptions on this stackoverflow [answer](https://stackoverflow.com/a/58652345/5162097).

Thanks for a great image and for the latest updates, much appreciated!

**Comment by VladimirButorin** [comment]
Hi, I also faced error by ndk instalation:

$ echo "y" | /opt/android-sdk-linux/tools/bin/sdkmanager --install "ndk;21.0.6113669"
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 5 more

**Comment by mindrunner** [comment]
@VladimirButorin can you still reproduce that issue with the changes from https://github.com/mindrunner/docker-android-sdk/pull/75?

**Comment by VladimirButorin** [comment]
sorry but still:
$ echo "y" | /opt/android-sdk-linux/tools/bin/sdkmanager --install "ndk;21.0.6113669"
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 5 more

do you like more git lab output?

**Comment by mindrunner** [comment]
Please make sure you always use the correct sdk-tools! (e.g. rather don't call them by absolute path, but use the version in PATH)

See: https://github.com/mindrunner/docker-android-sdk/pull/75#discussion_r682150525

**Comment by VladimirButorin** [comment]
Yes, that works, thank you. BTW path for sdkmanager not added into PATH variable:

root@c14ff04a9f9c:/opt/android-sdk-linux# find / | grep sdkmanager
/opt/android-sdk-linux/cmdline-tools/latest/lib/sdklib/libsdkmanager_lib.jar
/opt/android-sdk-linux/cmdline-tools/latest/lib/sdkmanager-classpath.jar
/opt/android-sdk-linux/cmdline-tools/latest/bin/sdkmanager
/opt/android-sdk-linux/tools/bin/sdkmanager
root@c14ff04a9f9c:/opt/android-sdk-linux# /opt/android-sdk-linux/cmdline-tools/latest/bin/sdkmanager --install "ndk;21.0.6113669"
[=======================================] 100% Unzipping... android-ndk-r21/wrap
root@c14ff04a9f9c:/opt/android-sdk-linux# $path
root@c14ff04a9f9c:/opt/android-sdk-linux# $PATH
bash: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin: No such file or directory
root@c14ff04a9f9c:/opt/android-sdk-linux#

**Comment by mindrunner** [comment]
Yeap, you need to export the `tools/android-env.sh` before. Not sure what your goal is, but normally there should be no reason to do things manually.

If you need to install a specific version of a package you should rather mount in a modified `package-list.txt` and/or even better file a Pull Request :)

**Comment by VladimirButorin** [comment]
OK, thank you!
